spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-188.railway.app:8009/railway
    username: postgres
    password: TwZ2Ix8iLlT8Mikd6yUF
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect